name: Moon CI
on:
  push:
    branches:
      - main
  pull_request: {}
env:
  GIT_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
jobs:
  ci:
    name: Moon CI
    runs-on: ubuntu-latest
    env:
      MOON_TOOLCHAIN_FORCE_GLOBALS: "true"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Moon CI Setup
        uses: ./.github/actions/moon-ci-setup
      - name: Test
        run: ./node_modules/.bin/moon ci :test
        shell: bash
